"""
Smoke-test M2's Step 1+2 graph (agent_module/pipeline.py) against REAL M1
output — not a hand-authored mock. Added alongside run_pipeline_draft_test.py
and run_pipeline.py (which point at m1_output_draft_proposal.json and
m1_sample_output.json respectively); nothing existing was replaced.

sample_data/m1_real_sample_output.json / m1_real_sample_batch.json were
generated by actually running ingestion/pipeline.py against
ingestion/incoming/dirty_sample.csv and decrypting the resulting
staging/dirty_sample.json.enc with ingestion/decrypt_staging.py - these
are M1's genuine CostLineItem field names (linked_account_id, service,
usage_type, region, usage_start_date, blended_cost, usage_quantity, tags),
including two PII-masked tag values, not an approximation of them.

Before running this for real: this graph's normalise_node makes a real LLM
call (OpenRouter, via build_normalise_chain) - it needs OPENROUTER_API_KEY in
agents/.env (copy .env.example -> .env and fill it in). No .env existed
in this repo as of writing this script, so the first run below is expected to
fail at that call until a key is added - see the static schema-gap check
below for what to expect independent of that key.

Known schema gap, findable without ever calling the LLM: Step 1's target
schema (schemas.NormalizedCostRecord) requires resource_id, period_end,
currency, and usage_unit as non-optional fields. Real M1 output has NONE of
these - M1's CostLineItem doesn't carry them at all. Every real M1 record
will force the LLM to invent values for four required fields on every call.
This script prints that gap explicitly before attempting the graph run.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from dotenv import load_dotenv

from agent_module.pipeline import build_pipeline_graph
from agent_module.schemas import NormalizedCostRecord

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

_REAL_M1_SINGLE = Path("sample_data/m1_real_sample_output.json")
_REAL_M1_BATCH = Path("sample_data/m1_real_sample_batch.json")

_STEP_LABELS = [
    "State BEFORE Step 1 (normalise)",
    "State AFTER Step 1 (normalise)",
    "State AFTER Step 2 (enrich)",
]


def print_schema_gap(raw_record: dict) -> None:
    required_fields = [
        name for name, field in NormalizedCostRecord.model_fields.items()
        if field.is_required()
    ]
    missing = [f for f in required_fields if f not in raw_record]
    print("=" * 70)
    print("Static schema-gap check (no LLM call, no network) — real M1 record")
    print("=" * 70)
    print(f"Step 1 target schema requires: {required_fields}")
    print(f"Real M1 record is missing:     {missing}")
    if missing:
        print("-> The LLM will have to invent these on every real M1 record.")
        print("   Fix options: make them Optional in NormalizedCostRecord, or")
        print("   have M1 emit stub values, or drop them from the schema if")
        print("   nothing downstream actually needs them.")
    print()


def print_state(label: str, state: dict) -> None:
    print(f"\n--- {label} ---")
    print(json.dumps(state, indent=2, default=str))


def run_once(graph, raw_record: dict, run_label: str) -> None:
    print("=" * 70)
    print(run_label)
    print("=" * 70)

    initial_state = {
        "raw_record": raw_record,
        "normalized_record": None,
        "cache_hit": None,
        "normalise_latency_seconds": None,
        "business_tags": None,
        "pricing_context": None,
    }

    for i, state in enumerate(graph.stream(initial_state, stream_mode="values")):
        label = _STEP_LABELS[i] if i < len(_STEP_LABELS) else f"State after step {i}"
        print_state(label, state)


def main() -> None:
    load_dotenv()

    with _REAL_M1_SINGLE.open("r", encoding="utf-8") as f:
        single_record = json.load(f)

    print_schema_gap(single_record)

    print("Attempting the real graph run (requires OPENROUTER_API_KEY)...")
    graph = build_pipeline_graph()

    run_once(graph, single_record, "RUN 1 — single real M1 record (clean, no PII)")

    with _REAL_M1_BATCH.open("r", encoding="utf-8") as f:
        batch = json.load(f)

    for i, record in enumerate(batch, start=1):
        run_once(graph, record, f"BATCH RUN {i}/{len(batch)} — real M1 record (may include masked PII in tags)")


if __name__ == "__main__":
    main()
